### Site Settings ###
title       : Shashank Priyadarshi
keywords    : Topics in Devops, Android, bioinformatics, and Space Exploration. 
description : >-
              :rocket: An electron in a Cosmos :rocket:  <br> <br> Android Developer <br>Open source enthusiast <br> <a href = "https://www.amrita.edu/"> Student at Amrita Vishwa Vidyapeetham</a> <br>  <a href="https://amfoss.in/" title = "amFOSS"> Member at amFOSS</a> <br> <a href="https://robusttechie.github.io/docs/cv.pdf" title="Open my CV">Check out my CV</a> 
baseurl     : ""     
repository  : robustTechie.github.io
remote_theme: robustTechie/portfolYOU



### Plugins ###
plugins:
  - jemoji
  - jekyll-sitemap

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  
### Author Info ###
author:
  name              : Shashank Priyadarshi
  image             : assets/profileImg1.jpg
# behance           : your_username
# dribbble          : your_username
  email             : s.priyadarshi629@gmail.com
  github            : robustTechie
  gitlab            : robustTechie
  linkedin          : robusttechie
  twitter           : robustTechie
  facebook          : shashank629
  instagram         : __.shashank
  
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  
# vimeo             : your_username
# youtube           : your_channel_name

### Disqus ###
disqus: https-robusttechie-github-io

### Analytics ###
analytics:
  enabled: fales  # Set false to disable analytics feature
  google:
    tracking_id: UA-163302221-1 # your google analytics tracking-id

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
